2018-03-10T16:12:19.7510958+01:00 0HLC6J58LVPP8:00000001 [INF] Request starting HTTP/1.1 POST http://192.168.10.10:3471/api/Post/create application/json 5618381 (ca22a1cb)
2018-03-10T16:12:19.8687778+01:00 0HLC6J58LVPP8:00000001 [INF] Policy execution failed. (12a644ed)
2018-03-10T16:12:19.8695728+01:00 0HLC6J58LVPP8:00000001 [INF] Request origin "file://" does not have permission to access the resource. (a03d560b)
2018-03-10T16:12:20.2743424+01:00 0HLC6J58LVPP8:00000001 [INF] Successfully validated the token. (60169667)
2018-03-10T16:12:20.2755217+01:00 0HLC6J58LVPP8:00000001 [INF] AuthenticationScheme: "Bearer" was successfully authenticated. (1805f3b3)
2018-03-10T16:12:20.5719536+01:00 0HLC6J58LVPP8:00000001 [INF] Executed action "EatlistApi.Controllers.PostController.Post (EatlistApi)" in 91.2156ms (afa2e885)
2018-03-10T16:12:20.6231311+01:00 0HLC6J58LVPP8:00000001 [ERR] Connection id ""0HLC6J58LVPP8"", Request id ""0HLC6J58LVPP8:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.NullReferenceException: Object reference not set to an instance of an object.
   at EatlistApi.Controllers.BaseController..ctor() in \\192.168.10.10\wwwroot\EatListN\EatlistApi\Controllers\BaseController.cs:line 24
   at EatlistApi.Controllers.PostController..ctor(ILogger`1 log) in \\192.168.10.10\wwwroot\EatListN\EatlistApi\Controllers\PostController.cs:line 30
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-03-10T16:12:21.9480220+01:00 0HLC6J58LVPP8:00000001 [INF] Request finished in 2213.4112ms 500  (791a596a)
2018-03-10T16:32:36.0592044+01:00 0HLC6J58LVPP9:00000001 [INF] Request starting HTTP/1.1 POST http://127.0.0.1:4230/iisintegration  0 (ca22a1cb)
2018-03-10T16:32:36.0602220+01:00 0HLC6J58LVPP9:00000001 [INF] Request finished in 1.0892ms 202  (791a596a)
